# Generated by Django 6.0 on 2025-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(choices=[('nextjs', 'Next.js'), ('nextauth', 'NextAuth'), ('react', 'React'), ('typescript', 'TypeScript'), ('tailwindcss', 'Tailwind CSS'), ('daisyui', 'DaisyUI'), ('pwa', 'PWA'), ('django', 'Django'), ('drf', 'Django REST Framework'), ('djoser', 'Djoser'), ('jwt', 'JWT'), ('channels', 'Django Channels'), ('celery', 'Celery'), ('redis', 'Redis'), ('daphne', 'Daphne'), ('wagtail', 'Wagtail'), ('bootstrap', 'Bootstrap'), ('htmx', 'HTMX'), ('alpinejs', 'Alpine.js'), ('jquery', 'jQuery'), ('postgresql', 'PostgreSQL'), ('cloudinary', 'Cloudinary'), ('docker', 'Docker'), ('railway', 'Railway'), ('heroku', 'Heroku'), ('vercel', 'Vercel'), ('github', 'GitHub'), ('linux', 'Linux')], max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('intro', models.CharField(max_length=150, unique=True)),
                ('docs', models.TextField()),
                ('image', models.ImageField(upload_to='project_image/')),
                ('tech', models.ManyToManyField(to='portfolio.tech')),
            ],
        ),
    ]
