# Generated by Django 6.0 on 2025-12-06 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tech_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
