# Generated by Django 6.0 on 2025-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_options_alter_tech_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(choices=[('nextjs', 'Next.js'), ('nextauth', 'NextAuth'), ('react', 'React'), ('typescript', 'TypeScript'), ('tailwindcss', 'Tailwind CSS'), ('daisyui', 'DaisyUI'), ('pwa', 'PWA'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('figma', 'Figma'), ('ux', 'UX'), ('agile', 'Agile Development'), ('markdownmd', 'Markdown.md'), ('pytest', 'PyTest'), ('jest', 'Jest'), ('flaskapi', 'FlaskApi'), ('django', 'Django'), ('drf', 'Django REST Framework'), ('djoser', 'Djoser'), ('jwt', 'JWT'), ('channels', 'Django Channels'), ('celery', 'Celery'), ('redis', 'Redis'), ('daphne', 'Daphne'), ('wagtail', 'Wagtail'), ('bootstrap', 'Bootstrap'), ('htmx', 'HTMX'), ('alpinejs', 'Alpine.js'), ('jquery', 'jQuery'), ('postgresql', 'PostgreSQL'), ('cloudinary', 'Cloudinary'), ('docker', 'Docker'), ('railway', 'Railway'), ('heroku', 'Heroku'), ('vercel', 'Vercel'), ('github', 'GitHub'), ('linux', 'Linux')], max_length=70),
        ),
    ]
