# Generated by Django 6.0 on 2025-12-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_tech_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='main_tech',
            field=models.ManyToManyField(related_name='projects_main_tech', to='portfolio.tech', verbose_name='Main Technologies'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tech',
            field=models.ManyToManyField(related_name='projects_all_tech', to='portfolio.tech'),
        ),
    ]
