# Generated by Django 6.0 on 2025-12-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(choices=[('nextjs', 'Next.js'), ('nextauth', 'NextAuth'), ('react', 'React'), ('typescript', 'TypeScript'), ('tailwindcss', 'Tailwind CSS'), ('daisyui', 'DaisyUI'), ('pwa', 'PWA'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('figma', 'Figma'), ('ux', 'UX'), ('agiledevelopment', 'Agile Development'), ('markdownmd', 'Markdown.md'), ('pytest', 'PyTest'), ('jest', 'Jest'), ('flaskapi', 'FlaskApi'), ('django', 'Django'), ('drf', 'DRF'), ('djoser', 'Djoser'), ('jwt', 'JWT'), ('djangochannels', 'Django Channels'), ('celery', 'Celery'), ('redis', 'Redis'), ('daphne', 'Daphne'), ('wagtail', 'Wagtail'), ('bootstrap', 'Bootstrap'), ('htmx', 'HTMX'), ('alpinejs', 'Alpine.js'), ('jquery', 'jQuery'), ('postgresql', 'PostgreSQL'), ('cloudinary', 'Cloudinary'), ('docker', 'Docker'), ('railway', 'Railway'), ('heroku', 'Heroku'), ('vercel', 'Vercel'), ('github', 'GitHub'), ('linux', 'Linux')], max_length=70),
        ),
    ]
