# Generated by Django 6.0 on 2025-12-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_tech_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='documents/certificates/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/resume/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(choices=[('nextjs', 'Next.js'), ('designthinking', 'Design Thinking'), ('react', 'React'), ('typescript', 'TypeScript'), ('tailwindcss', 'Tailwind CSS'), ('daisyui', 'DaisyUI'), ('pwa', 'PWA'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('figma', 'Figma'), ('ux', 'UX'), ('agiledevelopment', 'Agile Development'), ('markdownmd', 'Markdown.md'), ('pytest', 'PyTest'), ('jest', 'Jest'), ('flaskapi', 'FlaskApi'), ('django', 'Django'), ('drf', 'DRF'), ('djoser', 'Djoser'), ('jwt', 'JWT'), ('djangochannels', 'Django Channels'), ('celery', 'Celery'), ('redis', 'Redis'), ('daphne', 'Daphne'), ('wagtail', 'Wagtail'), ('bootstrap', 'Bootstrap'), ('htmx', 'HTMX'), ('alpinejs', 'Alpine.js'), ('jquery', 'jQuery'), ('postgresql', 'PostgreSQL'), ('cloudinary', 'Cloudinary'), ('docker', 'Docker'), ('railway', 'Railway'), ('heroku', 'Heroku'), ('vercel', 'Vercel'), ('github', 'GitHub'), ('linux', 'Linux')], max_length=70),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
        ),
    ]
