# Generated by Django 6.0 on 2025-12-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_education_period_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('course', 'start_date', 'end_date')},
        ),
    ]
