# Generated by Django 6.0 on 2025-12-07 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_contact_alter_skill_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('vision_intro', models.TextField()),
                ('principles_title', models.CharField()),
                ('principles_text', models.TextField()),
                ('long_term_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('long_term_title', models.CharField()),
                ('long_term_text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Visons',
            },
        ),
    ]
