# Generated by Django 6.0 on 2025-12-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_visons'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('static', 'Static Websites'), ('interactive', 'Interactive Frontend'), ('cli', 'CLI Apps'), ('fullstack', 'Full-Stack Web App'), ('ecommerce', 'E-Commerce Web App')], default='static', max_length=20),
        ),
    ]
