# Generated by Django 6.0 on 2025-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
