# Generated by Django 6.0 on 2025-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_certificate_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('plan', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='about',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.RemoveField(
            model_name='visons',
            name='long_term_date',
        ),
        migrations.RemoveField(
            model_name='visons',
            name='long_term_text',
        ),
        migrations.RemoveField(
            model_name='visons',
            name='long_term_title',
        ),
        migrations.RemoveField(
            model_name='visons',
            name='principles_text',
        ),
        migrations.AddField(
            model_name='visons',
            name='long_term_list',
            field=models.ManyToManyField(to='portfolio.longterm'),
        ),
        migrations.AddField(
            model_name='visons',
            name='principles_list',
            field=models.ManyToManyField(to='portfolio.principle'),
        ),
    ]
