# Generated by Django 6.0 on 2025-12-13 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_longterm_principle_remove_certificate_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('sub_title', models.CharField()),
                ('vision_intro', models.TextField()),
                ('principles_title', models.CharField()),
                ('longterm_title', models.CharField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Visons',
            },
        ),
        migrations.RemoveField(
            model_name='longterm',
            name='plan',
        ),
        migrations.AddField(
            model_name='longterm',
            name='vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_list', to='portfolio.visions'),
        ),
        migrations.AddField(
            model_name='principle',
            name='vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principles_list', to='portfolio.visions'),
        ),
        migrations.DeleteModel(
            name='Visons',
        ),
    ]
