# Generated by Django 6.0 on 2025-12-13 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_visions_remove_longterm_plan_longterm_vision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('vision_intro', models.TextField()),
                ('principles_title', models.CharField()),
                ('principles_text', models.TextField()),
                ('long_term_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('long_term_title', models.CharField()),
                ('long_term_text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Visons',
            },
        ),
        migrations.RemoveField(
            model_name='principle',
            name='vision',
        ),
        migrations.AddField(
            model_name='certificate',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('static', 'Static Websites'), ('interactive', 'Interactive Frontend'), ('cli', 'CLI Apps'), ('fullstack', 'Full-Stack Web App'), ('ecommerce', 'E-Commerce Web App')], default='static', max_length=20),
        ),
        migrations.DeleteModel(
            name='LongTerm',
        ),
        migrations.DeleteModel(
            name='Principle',
        ),
        migrations.DeleteModel(
            name='Visions',
        ),
    ]
