# Generated by Django 6.0 on 2025-12-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_longterm_principle_visions_delete_visons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longterm',
            name='plan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='longterm',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='principle',
            name='content',
            field=models.CharField(),
        ),
    ]
