# Generated by Django 6.0 on 2025-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_longterm_plan_alter_longterm_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longterm',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='longterm',
            name='key',
            field=models.SlugField(blank=True, help_text='Stable identifier (used in frontend logic, not shown to users)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='longterm',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='longterm',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
