# Generated by Django 6.0 on 2025-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_longterm_options_longterm_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longterm',
            name='key',
        ),
        migrations.AddField(
            model_name='principle',
            name='key',
            field=models.SlugField(blank=True, help_text='Stable identifier (used in frontend logic, not shown to users)', null=True, unique=True),
        ),
    ]
