# Generated by Django 6.0 on 2025-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_longterm_key_principle_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='key',
            field=models.SlugField(default='temp', help_text='Stable identifier (used in frontend logic, not shown to users)', unique=True),
        ),
    ]
