# Generated by Django 6.0 on 2025-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_principle_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(choices=[('nextjs', 'Next.js'), ('designthinking', 'Design Thinking'), ('react', 'React'), ('typescript', 'TypeScript'), ('tailwindcss', 'Tailwind CSS'), ('daisyui', 'DaisyUI'), ('pwa', 'PWA'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('figma', 'Figma'), ('ux', 'UX'), ('agiledevelopment', 'Agile Development'), ('markdownmd', 'Markdown.md'), ('pytest', 'PyTest'), ('jest', 'Jest'), ('flaskapi', 'FlaskApi'), ('django', 'Django'), ('drf', 'DRF'), ('djoser', 'Djoser'), ('jwt', 'JWT'), ('djangochannels', 'Django Channels'), ('celery', 'Celery'), ('redis', 'Redis'), ('daphne', 'Daphne'), ('wagtail', 'Wagtail'), ('bootstrap', 'Bootstrap'), ('htmx', 'HTMX'), ('alpinejs', 'Alpine.js'), ('jquery', 'jQuery'), ('postgresql', 'PostgreSQL'), ('cloudinary', 'Cloudinary'), ('docker', 'Docker'), ('railway', 'Railway'), ('heroku', 'Heroku'), ('vercel', 'Vercel'), ('github', 'GitHub'), ('linux', 'Linux'), ('tenants', 'Tenants'), ('S3', 'S3')], max_length=70),
        ),
    ]
