# Generated by Django 6.0 on 2025-12-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_tech_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='source_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
