# Generated by Django 5.2.7 on 2025-12-16 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='visions',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='visions',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localdate),
        ),
    ]
