# Generated by Django 5.2.7 on 2025-12-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_assessmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentimage',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
