# Generated by Django 5.2.7 on 2025-12-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_assessmentimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('static', 'Static Websites'), ('interactive', 'Interactive Frontend'), ('cli', 'CLI Apps'), ('fullstack', 'Full-Stack Web App'), ('ecommerce', 'E-Commerce Web App'), ('pwa', 'Progressive Web App (PWA)')], default='static', max_length=20),
        ),
    ]
