# Generated by Django 5.2.7 on 2025-12-20 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='docs',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
