# Generated by Django 5.2.7 on 2025-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='docs_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='docs_footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
